const destination = [
  {
    City: "Los Angeles",
    Air_Quality_Index: 50,
    Happiness_Score: 6.8,
    Cost_of_Living_Index: 90,
    Region: "North America",
    Country: "US",
    AvgTemperature: 16.9825688073,
    Traffic_enc: 1,
    IATA: ["LAX", "LSQ", "WHP"],
    "Airport name": [
      "Los Angeles International Airport",
      "Mar\u00eda Dolores Airport",
      "Whiteman Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 20.0,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 87.09,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 2568.47,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1952.66,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 4668.57,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 3599.83,
    Pays: "US",
    "Vol USD": 611.0,
    "S\u00e9jour USD": 1538.0,
    "Sur place USD": 106.0,
    Latitude: 34.0536909,
    Longitude: -118.242766,
  },
  {
    City: "Chicago",
    Air_Quality_Index: 55,
    Happiness_Score: 7.0,
    Cost_of_Living_Index: 85,
    Region: "North America",
    Country: "US",
    AvgTemperature: 10.1915752234,
    Traffic_enc: 1,
    IATA: ["MDW", "ORD"],
    "Airport name": [
      "Chicago Midway International Airport",
      "Chicago O'Hare International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 20.0,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 80.0,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1969.12,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1436.82,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 3911.76,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 2450.0,
    Pays: "US",
    "Vol USD": 611.0,
    "S\u00e9jour USD": 1538.0,
    "Sur place USD": 106.0,
    Latitude: 41.8755616,
    Longitude: -87.6244212,
  },
  {
    City: "London",
    Air_Quality_Index: 60,
    Happiness_Score: 7.2,
    Cost_of_Living_Index: 110,
    Region: "Europe",
    Country: "United Kingdom",
    AvgTemperature: 11.3140153968,
    Traffic_enc: 2,
    IATA: ["BQH", "LCY", "LGW", "LHR", "LOZ", "LTN", "NHT", "STN", "YXU"],
    "Airport name": [
      "London Biggin Hill Airport",
      "London City Airport",
      "London Gatwick Airport",
      "London Heathrow Airport",
      "London-Corbin Airport/Magee Field",
      "London Luton Airport",
      "RAF Northolt",
      "London Stansted Airport",
      "London Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 18.02,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 80.48,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 2311.99,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1669.19,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 3875.48,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 2730.82,
    Pays: "United Kingdom",
    "Vol USD": 109.0,
    "S\u00e9jour USD": 1266.0,
    "Sur place USD": 118.0,
    Latitude: 51.5074456,
    Longitude: -0.1277653,
  },
  {
    City: "Paris",
    Air_Quality_Index: 65,
    Happiness_Score: 6.9,
    Cost_of_Living_Index: 95,
    Region: "Europe",
    Country: "France",
    AvgTemperature: 11.6337146557,
    Traffic_enc: 2,
    IATA: ["CDG", "LBG", "ORY", "PHT", "PRX"],
    "Airport name": [
      "Charles de Gaulle International Airport",
      "Paris-Le Bourget Airport",
      "Paris-Orly Airport",
      "Henry County Airport",
      "Cox Field",
    ],
    "Meal, Inexpensive Restaurant (USD)": 15.58,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 62.32,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1325.47,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 978.26,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2968.63,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 2018.27,
    Pays: "France",
    "Vol USD": 76.0,
    "S\u00e9jour USD": 654.0,
    "Sur place USD": 98.0,
    Latitude: 48.8588897,
    Longitude: 2.3200410217,
  },
  {
    City: "Tokyo",
    Air_Quality_Index: 70,
    Happiness_Score: 6.0,
    Cost_of_Living_Index: 120,
    Region: "Asia",
    Country: "Japan",
    AvgTemperature: 16.1463894285,
    Traffic_enc: 2,
    IATA: ["HND", "NRT"],
    "Airport name": [
      "Tokyo Haneda International Airport",
      "Narita International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 7.22,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 43.31,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1105.83,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 638.41,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2424.17,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1314.14,
    Pays: "Japan",
    "Vol USD": 699.0,
    "S\u00e9jour USD": 3001.0,
    "Sur place USD": 90.0,
    Latitude: 35.6821936,
    Longitude: 139.762221,
  },
  {
    City: "Seoul",
    Air_Quality_Index: 75,
    Happiness_Score: 5.8,
    Cost_of_Living_Index: 105,
    Region: "Asia",
    Country: "South Korea",
    AvgTemperature: 11.5988740197,
    Traffic_enc: 2,
    IATA: ["GMP", "ICN"],
    "Airport name": [
      "Gimpo International Airport",
      "Incheon International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 7.16,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 52.77,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 809.83,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 583.6,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2621.05,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1683.74,
    Pays: "South Korea",
    "Vol USD": 655.0,
    "S\u00e9jour USD": 1570.0,
    "Sur place USD": 78.0,
    Latitude: 37.5666791,
    Longitude: 126.9782914,
  },
  {
    City: "Sydney",
    Air_Quality_Index: 30,
    Happiness_Score: 7.8,
    Cost_of_Living_Index: 115,
    Region: "Australia/South Pacific",
    Country: "Australia",
    AvgTemperature: 14.1940307456,
    Traffic_enc: 0,
    IATA: ["BWU", "SYD", "YQY"],
    "Airport name": [
      "Sydney Bankstown Airport",
      "Sydney Kingsford Smith International Airport",
      "Sydney / J.A. Douglas McCurdy Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 13.41,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 80.47,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1657.31,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1243.61,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 3318.55,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 2132.95,
    Pays: "Australia",
    "Vol USD": 1201.0,
    "S\u00e9jour USD": 3908.0,
    "Sur place USD": 119.0,
    Latitude: -33.8698439,
    Longitude: 151.2082848,
  },
  {
    City: "Istanbul",
    Air_Quality_Index: 85,
    Happiness_Score: 6.8,
    Cost_of_Living_Index: 75,
    Region: "Middle East",
    Country: "Turkey",
    AvgTemperature: 15.2516188215,
    Traffic_enc: 2,
    IATA: ["ISL", "IST", "SAW"],
    "Airport name": [
      "Istanbul New Airport",
      "Istanbul International Airport",
      "Sabiha G\u00f6k\u00e7en International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 5.36,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 24.14,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 538.89,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 312.32,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1033.08,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 576.51,
    Pays: "Turkey",
    "Vol USD": 207.0,
    "S\u00e9jour USD": 449.0,
    "Sur place USD": 60.0,
    Latitude: 41.006381,
    Longitude: 28.9758715,
  },
  {
    City: "Rio de Janeiro",
    Air_Quality_Index: 55,
    Happiness_Score: 6.5,
    Cost_of_Living_Index: 80,
    Region: "South/Central America & Carribean",
    Country: "Brazil",
    AvgTemperature: 22.8871319782,
    Traffic_enc: 1,
    IATA: ["SNZ"],
    "Airport name": ["Santa Cruz Air Force Base"],
    "Meal, Inexpensive Restaurant (USD)": 6.52,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 27.95,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 385.92,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 247.48,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 773.3,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 558.24,
    Pays: "Brazil",
    "Vol USD": 874.0,
    "S\u00e9jour USD": 1547.0,
    "Sur place USD": 72.0,
    Latitude: -22.9110137,
    Longitude: -43.2093727,
  },
  {
    City: "Toronto",
    Air_Quality_Index: 40,
    Happiness_Score: 7.1,
    Cost_of_Living_Index: 95,
    Region: "North America",
    Country: "Canada",
    AvgTemperature: 8.665743479,
    Traffic_enc: 1,
    IATA: ["YKZ", "YTZ", "YYZ", "YZD"],
    "Airport name": [
      "Buttonville Municipal Airport",
      "Billy Bishop Toronto City Centre Airport",
      "Lester B. Pearson International Airport",
      "Downsview Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 18.61,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 81.9,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1696.63,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1435.71,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2745.86,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 2296.47,
    Pays: "Canada",
    "Vol USD": 764.0,
    "S\u00e9jour USD": 1998.0,
    "Sur place USD": 102.0,
    Latitude: 43.6534817,
    Longitude: -79.3839347,
  },
  {
    City: "Mexico City",
    Air_Quality_Index: 90,
    Happiness_Score: 5.2,
    Cost_of_Living_Index: 65,
    Region: "North America",
    Country: "Mexico",
    AvgTemperature: 16.694711279,
    Traffic_enc: 3,
    IATA: ["MEX"],
    "Airport name": ["Licenciado Benito Juarez International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 7.78,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 39.95,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 789.83,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 484.05,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1498.8,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 894.19,
    Pays: "Mexico",
    "Vol USD": 710.0,
    "S\u00e9jour USD": 1392.0,
    "Sur place USD": 56.0,
    Latitude: 19.4326296,
    Longitude: -99.1331785,
  },
  {
    City: "Bangkok",
    Air_Quality_Index: 110,
    Happiness_Score: 4.0,
    Cost_of_Living_Index: 50,
    Region: "Asia",
    Country: "Thailand",
    AvgTemperature: 22.480047712,
    Traffic_enc: 2,
    IATA: ["BKK", "DMK"],
    "Airport name": [
      "Suvarnabhumi Airport",
      "Don Mueang International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 2.6,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 28.09,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 584.77,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 280.92,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1994.97,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 915.48,
    Pays: "Thailand",
    "Vol USD": 710.0,
    "S\u00e9jour USD": 1110.0,
    "Sur place USD": 44.0,
    Latitude: 13.7524938,
    Longitude: 100.4935089,
  },
  {
    City: "Buenos Aires",
    Air_Quality_Index: 60,
    Happiness_Score: 6.1,
    Cost_of_Living_Index: 60,
    Region: "South/Central America & Carribean",
    Country: "Argentina",
    AvgTemperature: 16.8360553517,
    Traffic_enc: 2,
    IATA: ["AEP", "EZE"],
    "Airport name": [
      "Jorge Newbery Airpark",
      "Ministro Pistarini International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 6.4,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 25.0,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 308.45,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 225.84,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 627.35,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 444.68,
    Pays: "Argentina",
    "Vol USD": 983.0,
    "S\u00e9jour USD": 3027.0,
    "Sur place USD": 85.0,
    Latitude: -34.6073387,
    Longitude: -58.4432852,
  },
  {
    City: "Amsterdam",
    Air_Quality_Index: 50,
    Happiness_Score: 7.9,
    Cost_of_Living_Index: 105,
    Region: "Europe",
    Country: "The Netherlands",
    AvgTemperature: 10.4544871334,
    Traffic_enc: 0,
    IATA: ["AMS"],
    "Airport name": ["Amsterdam Airport Schiphol"],
    "Meal, Inexpensive Restaurant (USD)": 19.22,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 83.1,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1769.11,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1512.73,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2970.6,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 2175.95,
    Pays: "The Netherlands",
    "Vol USD": 87.0,
    "S\u00e9jour USD": 633.0,
    "Sur place USD": 112.0,
    Latitude: 52.3730796,
    Longitude: 4.8924534,
  },
  {
    City: "Cairo",
    Air_Quality_Index: 115,
    Happiness_Score: 3.5,
    Cost_of_Living_Index: 55,
    Region: "Africa",
    Country: "Egypt",
    AvgTemperature: 22.196375039,
    Traffic_enc: 3,
    IATA: ["CAI", "CIR"],
    "Airport name": ["Cairo International Airport", "Cairo Regional Airport"],
    "Meal, Inexpensive Restaurant (USD)": 4.07,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 20.36,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 197.56,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 113.99,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 396.99,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 234.28,
    Pays: "Egypt",
    "Vol USD": 306.0,
    "S\u00e9jour USD": 574.0,
    "Sur place USD": 49.0,
    Latitude: 30.0443879,
    Longitude: 31.2357257,
  },
  {
    City: "Moscow",
    Air_Quality_Index: 80,
    Happiness_Score: 5.8,
    Cost_of_Living_Index: 70,
    Region: "Europe",
    Country: "Russia",
    AvgTemperature: 5.5144434851,
    Traffic_enc: 2,
    IATA: ["CKL", "DME", "OSF", "SVO", "VKO", "ZIA"],
    "Airport name": [
      "Chkalovskiy Air Base",
      "Domodedovo International Airport",
      "Ostafyevo International Airport",
      "Sheremetyevo International Airport",
      "Vnukovo International Airport",
      "Zhukovsky International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 13.1,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 65.5,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1167.72,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 674.05,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2240.93,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1194.85,
    Pays: "Russia",
    "Vol USD": 207.0,
    "S\u00e9jour USD": 1580.0,
    "Sur place USD": 80.0,
    Latitude: 55.625578,
    Longitude: 37.6063916,
  },
  {
    City: "Singapore",
    Air_Quality_Index: 60,
    Happiness_Score: 7.0,
    Cost_of_Living_Index: 125,
    Region: "Asia",
    Country: "Singapore",
    AvgTemperature: 27.5857795525,
    Traffic_enc: 2,
    IATA: ["QPG", "SIN", "TGA"],
    "Airport name": [
      "Paya Lebar Air Base",
      "Singapore Changi Airport",
      "Tengah Air Base",
    ],
    "Meal, Inexpensive Restaurant (USD)": 10.92,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 60.06,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 2660.73,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1965.72,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 5317.61,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 3466.53,
    Pays: "Singapore",
    "Vol USD": 688.0,
    "S\u00e9jour USD": 2143.0,
    "Sur place USD": 83.0,
    Latitude: 1.357107,
    Longitude: 103.8194992,
  },
  {
    City: "Dubai",
    Air_Quality_Index: 120,
    Happiness_Score: 6.0,
    Cost_of_Living_Index: 110,
    Region: "Middle East",
    Country: "United Arab Emirates",
    AvgTemperature: 28.3181284025,
    Traffic_enc: 1,
    IATA: ["DXB", "NHD"],
    "Airport name": ["Dubai International Airport", "Al Minhad Air Base"],
    "Meal, Inexpensive Restaurant (USD)": 12.25,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 81.68,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1752.39,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1024.09,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 3270.19,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1985.29,
    Pays: "United Arab Emirates",
    "Vol USD": 328.0,
    "S\u00e9jour USD": 694.0,
    "Sur place USD": 82.0,
    Latitude: 25.2653471,
    Longitude: 55.2924914,
  },
  {
    City: "Hong Kong",
    Air_Quality_Index: 100,
    Happiness_Score: 5.5,
    Cost_of_Living_Index: 130,
    Region: "Asia",
    Country: "Hong Kong",
    AvgTemperature: 23.9237654987,
    Traffic_enc: 2,
    IATA: ["HKG"],
    "Airport name": ["Hong Kong International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 7.68,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 64.02,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 2284.16,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1629.08,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 4591.17,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 3015.71,
    Pays: "Hong Kong",
    "Vol USD": 764.0,
    "S\u00e9jour USD": 1944.0,
    "Sur place USD": 153.0,
    Latitude: 22.2793278,
    Longitude: 114.1628131,
  },
  {
    City: "Barcelona",
    Air_Quality_Index: 35,
    Happiness_Score: 7.7,
    Cost_of_Living_Index: 90,
    Region: "Europe",
    Country: "Spain",
    AvgTemperature: 16.2607022088,
    Traffic_enc: 1,
    IATA: ["BCN", "BLA"],
    "Airport name": [
      "Barcelona International Airport",
      "General Jos\u00e9 Antonio Anzoategui International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 14.54,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 62.32,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1075.89,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 840.13,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1772.54,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1368.73,
    Pays: "Spain",
    "Vol USD": 71.0,
    "S\u00e9jour USD": 453.0,
    "Sur place USD": 78.0,
    Latitude: 41.3828939,
    Longitude: 2.1774322,
  },
  {
    City: "Lisbon",
    Air_Quality_Index: 40,
    Happiness_Score: 7.8,
    Cost_of_Living_Index: 75,
    Region: "Europe",
    Country: "Portugal",
    AvgTemperature: 16.5876501907,
    Traffic_enc: 0,
    IATA: ["LIS"],
    "Airport name": ["Humberto Delgado Airport"],
    "Meal, Inexpensive Restaurant (USD)": 12.46,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 51.93,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1215.82,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 801.79,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2118.56,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1302.23,
    Pays: "Portugal",
    "Vol USD": 142.0,
    "S\u00e9jour USD": 655.0,
    "Sur place USD": 75.0,
    Latitude: 38.7077507,
    Longitude: -9.1365919,
  },
  {
    City: "Melbourne",
    Air_Quality_Index: 45,
    Happiness_Score: 7.9,
    Cost_of_Living_Index: 115,
    Region: "Australia/South Pacific",
    Country: "Australia",
    AvgTemperature: 18.1774468187,
    Traffic_enc: 0,
    IATA: ["AVV", "MBW", "MEL", "MLB"],
    "Airport name": [
      "Avalon Airport",
      "Melbourne Moorabbin Airport",
      "Melbourne International Airport",
      "Melbourne International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 15.42,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 80.47,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1226.45,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1003.98,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2271.62,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1560.59,
    Pays: "Australia",
    "Vol USD": 1201.0,
    "S\u00e9jour USD": 3908.0,
    "Sur place USD": 119.0,
    Latitude: -37.8142454,
    Longitude: 144.9631732,
  },
  {
    City: "Auckland",
    Air_Quality_Index: 35,
    Happiness_Score: 8.1,
    Cost_of_Living_Index: 100,
    Region: "Australia/South Pacific",
    Country: "New Zealand",
    AvgTemperature: 14.9520828837,
    Traffic_enc: 0,
    IATA: ["AKL", "WIK"],
    "Airport name": ["Auckland International Airport", "Waiheke Reeve Airport"],
    "Meal, Inexpensive Restaurant (USD)": 15.53,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 74.56,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1320.14,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1159.51,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2349.61,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1913.73,
    Pays: "New Zealand",
    "Vol USD": 1310.0,
    "S\u00e9jour USD": 2218.0,
    "Sur place USD": 119.0,
    Latitude: -36.852095,
    Longitude: 174.7631803,
  },
  {
    City: "Rome",
    Air_Quality_Index: 70,
    Happiness_Score: 6.7,
    Cost_of_Living_Index: 85,
    Region: "Europe",
    Country: "Italy",
    AvgTemperature: 15.6804566276,
    Traffic_enc: 2,
    IATA: ["CIA", "FCO", "REO", "RME", "RMG"],
    "Airport name": [
      "Ciampino\u2013G. B. Pastine International Airport",
      "Leonardo da Vinci\u2013Fiumicino Airport",
      "Rome State Airport",
      "Griffiss International Airport",
      "Richard B Russell Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 16.1,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 72.71,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1055.02,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 717.64,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2251.75,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1348.63,
    Pays: "Italy",
    "Vol USD": 72.0,
    "S\u00e9jour USD": 513.0,
    "Sur place USD": 98.0,
    Latitude: 41.8933203,
    Longitude: 12.4829321,
  },
  {
    City: "Athens",
    Air_Quality_Index: 75,
    Happiness_Score: 6.2,
    Cost_of_Living_Index: 70,
    Region: "Europe",
    Country: "Greece",
    AvgTemperature: 15.3521504014,
    Traffic_enc: 1,
    IATA: ["AHN", "ATH", "MMI"],
    "Airport name": [
      "Athens Ben Epps Airport",
      "Eleftherios Venizelos International Airport",
      "McMinn County Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 12.46,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 51.93,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 508.7,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 453.9,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 881.18,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 835.64,
    Pays: "Greece",
    "Vol USD": 218.0,
    "S\u00e9jour USD": 455.0,
    "Sur place USD": 64.0,
    Latitude: 33.9597677,
    Longitude: -83.376398,
  },
  {
    City: "Vienna",
    Air_Quality_Index: 30,
    Happiness_Score: 8.2,
    Cost_of_Living_Index: 95,
    Region: "Europe",
    Country: "Austria",
    AvgTemperature: 10.5817924551,
    Traffic_enc: 0,
    IATA: ["VIE"],
    "Airport name": ["Vienna International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 15.58,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 62.32,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 983.06,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 690.86,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1932.98,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1328.32,
    Pays: "Austria",
    "Vol USD": 131.0,
    "S\u00e9jour USD": 797.0,
    "Sur place USD": 108.0,
    Latitude: 48.2083537,
    Longitude: 16.3725042,
  },
  {
    City: "Dublin",
    Air_Quality_Index: 40,
    Happiness_Score: 7.0,
    Cost_of_Living_Index: 105,
    Region: "Europe",
    Country: "Ireland",
    AvgTemperature: 9.4815454349,
    Traffic_enc: 1,
    IATA: ["DBN", "DUB", "PSK"],
    "Airport name": [
      "W H 'Bud' Barron Airport",
      "Dublin Airport",
      "New River Valley Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 18.7,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 83.1,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1989.88,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1738.62,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 3599.73,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 2880.73,
    Pays: "Ireland",
    "Vol USD": 98.0,
    "S\u00e9jour USD": 923.0,
    "Sur place USD": 106.0,
    Latitude: 53.3493795,
    Longitude: -6.2605593,
  },
  {
    City: "Copenhagen",
    Air_Quality_Index: 35,
    Happiness_Score: 8.3,
    Cost_of_Living_Index: 110,
    Region: "Europe",
    Country: "Denmark",
    AvgTemperature: 8.3113593304,
    Traffic_enc: 0,
    IATA: ["CPH", "RKE"],
    "Airport name": [
      "Copenhagen Kastrup Airport",
      "Copenhagen Roskilde Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 19.55,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 111.74,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1705.63,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1278.77,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2593.58,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1985.3,
    Pays: "Denmark",
    "Vol USD": 131.0,
    "S\u00e9jour USD": 1348.0,
    "Sur place USD": 148.0,
    Latitude: 55.6867243,
    Longitude: 12.5700724,
  },
  {
    City: "Stockholm",
    Air_Quality_Index: 30,
    Happiness_Score: 8.0,
    Cost_of_Living_Index: 100,
    Region: "Europe",
    Country: "Sweden",
    AvgTemperature: 7.2741684054,
    Traffic_enc: 0,
    IATA: ["ARN", "BMA", "SMP"],
    "Airport name": [
      "Stockholm-Arlanda Airport",
      "Stockholm-Bromma Airport",
      "Stockholm Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 12.38,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 76.21,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1365.56,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1016.12,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2274.5,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1547.31,
    Pays: "Sweden",
    "Vol USD": 153.0,
    "S\u00e9jour USD": 1834.0,
    "Sur place USD": 129.0,
    Latitude: 59.3251172,
    Longitude: 18.0710935,
  },
  {
    City: "Oslo",
    Air_Quality_Index: 25,
    Happiness_Score: 8.5,
    Cost_of_Living_Index: 115,
    Region: "Europe",
    Country: "Norway",
    AvgTemperature: 4.9574289138,
    Traffic_enc: 0,
    IATA: ["OSL", "RYG"],
    "Airport name": ["Oslo Gardermoen Airport", "Moss Airport, Rygge"],
    "Meal, Inexpensive Restaurant (USD)": 20.11,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 108.58,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1405.05,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1144.04,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2296.3,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1822.67,
    Pays: "Norway",
    "Vol USD": 153.0,
    "S\u00e9jour USD": 2529.0,
    "Sur place USD": 170.0,
    Latitude: 59.9133301,
    Longitude: 10.7389701,
  },
  {
    City: "Helsinki",
    Air_Quality_Index: 20,
    Happiness_Score: 8.4,
    Cost_of_Living_Index: 90,
    Region: "Europe",
    Country: "Finland",
    AvgTemperature: 5.6911108713,
    Traffic_enc: 0,
    IATA: ["HEL", "HEM"],
    "Airport name": ["Helsinki Vantaa Airport", "Helsinki Malmi Airport"],
    "Meal, Inexpensive Restaurant (USD)": 13.5,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 83.1,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1041.66,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 830.09,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2085.59,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1440.51,
    Pays: "Finland",
    "Vol USD": 164.0,
    "S\u00e9jour USD": 1439.0,
    "Sur place USD": 134.0,
    Latitude: 60.1674881,
    Longitude: 24.9427473,
  },
  {
    City: "Prague",
    Air_Quality_Index: 65,
    Happiness_Score: 7.3,
    Cost_of_Living_Index: 80,
    Region: "Europe",
    Country: "Czech Republic",
    AvgTemperature: 8.6684773485,
    Traffic_enc: 1,
    IATA: ["PRG"],
    "Airport name": ["V\u00e1clav Havel Airport Prague"],
    "Meal, Inexpensive Restaurant (USD)": 8.65,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 43.26,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 945.17,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 704.73,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1677.54,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1206.79,
    Pays: "Czech Republic",
    "Vol USD": 87.0,
    "S\u00e9jour USD": 129.0,
    "Sur place USD": 51.0,
    Latitude: 50.0596288,
    Longitude: 14.4464592733,
  },
  {
    City: "Budapest",
    Air_Quality_Index: 70,
    Happiness_Score: 6.8,
    Cost_of_Living_Index: 75,
    Region: "Europe",
    Country: "Hungary",
    AvgTemperature: 10.6105894909,
    Traffic_enc: 1,
    IATA: ["BUD"],
    "Airport name": ["Budapest Liszt Ferenc International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 7.93,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 38.35,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 475.62,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 368.37,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 881.43,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 633.5,
    Pays: "Hungary",
    "Vol USD": 82.0,
    "S\u00e9jour USD": 513.0,
    "Sur place USD": 64.0,
    Latitude: 47.48138955,
    Longitude: 19.1460941269,
  },
  {
    City: "Warsaw",
    Air_Quality_Index: 75,
    Happiness_Score: 6.7,
    Cost_of_Living_Index: 70,
    Region: "Europe",
    Country: "Poland",
    AvgTemperature: 8.7644914502,
    Traffic_enc: 1,
    IATA: ["WAW", "WMI"],
    "Airport name": ["Warsaw Chopin Airport", "Modlin Airport"],
    "Meal, Inexpensive Restaurant (USD)": 7.78,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 44.43,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 778.49,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 592.63,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1446.57,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1104.41,
    Pays: "Poland",
    "Vol USD": 109.0,
    "S\u00e9jour USD": 1334.0,
    "Sur place USD": 54.0,
    Latitude: 52.2337172,
    Longitude: 21.0714322356,
  },
  {
    City: "Sofia",
    Air_Quality_Index: 80,
    Happiness_Score: 6.0,
    Cost_of_Living_Index: 60,
    Region: "Europe",
    Country: "Bulgaria",
    AvgTemperature: 7.3351919802,
    Traffic_enc: 2,
    IATA: ["SOF"],
    "Airport name": ["Sofia Airport"],
    "Meal, Inexpensive Restaurant (USD)": 10.62,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 37.17,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 437.61,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 330.07,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 821.13,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 564.04,
    Pays: "Bulgaria",
    "Vol USD": 104.0,
    "S\u00e9jour USD": 912.0,
    "Sur place USD": 57.0,
    Latitude: -15.2538402,
    Longitude: 48.2562163,
  },
  {
    City: "Belgrade",
    Air_Quality_Index: 85,
    Happiness_Score: 5.5,
    Cost_of_Living_Index: 55,
    Region: "Europe",
    Country: "Yugoslavia",
    AvgTemperature: 12.2404669401,
    Traffic_enc: 2,
    IATA: ["BEG"],
    "Airport name": ["Belgrade Nikola Tesla Airport"],
    "Meal, Inexpensive Restaurant (USD)": 7.96,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 31.86,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 635.45,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 397.77,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1139.04,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 723.86,
    Pays: "Yugoslavia",
    "Vol USD": 186.0,
    "S\u00e9jour USD": 1507.0,
    "Sur place USD": 55.0,
    Latitude: 44.8178131,
    Longitude: 20.4568974,
  },
  {
    City: "Lima",
    Air_Quality_Index: 100,
    Happiness_Score: 4.2,
    Cost_of_Living_Index: 55,
    Region: "South/Central America & Carribean",
    Country: "Peru",
    AvgTemperature: 19.2408038693,
    Traffic_enc: 3,
    IATA: ["AOH", "LIM"],
    "Airport name": [
      "Lima Allen County Airport",
      "Jorge Ch\u00e1vez International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 3.84,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 23.06,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 503.19,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 339.01,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 941.31,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 678.48,
    Pays: "Peru",
    "Vol USD": 1026.0,
    "S\u00e9jour USD": 2440.0,
    "Sur place USD": 46.0,
    Latitude: -12.0621065,
    Longitude: -77.0365256,
  },
  {
    City: "Bogota",
    Air_Quality_Index: 110,
    Happiness_Score: 5.0,
    Cost_of_Living_Index: 60,
    Region: "South/Central America & Carribean",
    Country: "Colombia",
    AvgTemperature: 12.913309111,
    Traffic_enc: 2,
    IATA: ["BOG"],
    "Airport name": ["El Dorado International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 3.06,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 18.34,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 320.94,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 253.16,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 590.05,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 449.67,
    Pays: "Colombia",
    "Vol USD": 830.0,
    "S\u00e9jour USD": 3038.0,
    "Sur place USD": 64.0,
    Latitude: 4.6533816,
    Longitude: -74.0836333,
  },
  {
    City: "Caracas",
    Air_Quality_Index: 115,
    Happiness_Score: 3.0,
    Cost_of_Living_Index: 50,
    Region: "South/Central America & Carribean",
    Country: "Venezuela",
    AvgTemperature: 25.7366732626,
    Traffic_enc: 3,
    IATA: ["CCS"],
    "Airport name": ["Sim\u00f3n Bol\u00edvar International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 10.0,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 50.0,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 383.33,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 322.22,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 831.25,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 587.5,
    Pays: "Venezuela",
    "Vol USD": 808.0,
    "S\u00e9jour USD": 1721.0,
    "Sur place USD": 74.0,
    Latitude: 10.5060934,
    Longitude: -66.9146008,
  },
  {
    City: "Quito",
    Air_Quality_Index: 120,
    Happiness_Score: 4.5,
    Cost_of_Living_Index: 55,
    Region: "South/Central America & Carribean",
    Country: "Equador",
    AvgTemperature: 5.7974241731,
    Traffic_enc: 2,
    IATA: ["UIO"],
    "Airport name": ["Mariscal Sucre International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 3.5,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 42.5,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 445.83,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 237.81,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 665.29,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 479.69,
    Pays: "Equador",
    "Vol USD": 874.0,
    "S\u00e9jour USD": 2041.0,
    "Sur place USD": 51.0,
    Latitude: -0.2201641,
    Longitude: -78.5123274,
  },
  {
    City: "Panama City",
    Air_Quality_Index: 125,
    Happiness_Score: 5.8,
    Cost_of_Living_Index: 60,
    Region: "South/Central America & Carribean",
    Country: "Panama",
    AvgTemperature: 26.4326630213,
    Traffic_enc: 1,
    IATA: ["PAM"],
    "Airport name": ["Tyndall Air Force Base"],
    "Meal, Inexpensive Restaurant (USD)": 8.0,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 50.0,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 908.95,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 510.29,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1784.21,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 973.68,
    Pays: "Panama",
    "Vol USD": 764.0,
    "S\u00e9jour USD": 1761.0,
    "Sur place USD": 68.0,
    Latitude: 30.1586518,
    Longitude: -85.6602936,
  },
  {
    City: "Havana",
    Air_Quality_Index: 135,
    Happiness_Score: 6.0,
    Cost_of_Living_Index: 50,
    Region: "South/Central America & Carribean",
    Country: "Cuba",
    AvgTemperature: 22.5782239493,
    Traffic_enc: 1,
    IATA: ["HAV", "UPB"],
    "Airport name": [
      "Jos\u00e9 Mart\u00ed International Airport",
      "Playa Baracoa Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 10.0,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 40.0,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 353.33,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 222.5,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1625.0,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 730.0,
    Pays: "Cuba",
    "Vol USD": 819.0,
    "S\u00e9jour USD": 1221.0,
    "Sur place USD": 64.0,
    Latitude: 23.135305,
    Longitude: -82.3589631,
  },
  {
    City: "Santo Domingo",
    Air_Quality_Index: 140,
    Happiness_Score: 5.5,
    Cost_of_Living_Index: 55,
    Region: "South/Central America & Carribean",
    Country: "Dominican Republic",
    AvgTemperature: 18.4531990166,
    Traffic_enc: 2,
    IATA: ["SDQ", "STD"],
    "Airport name": [
      "Las Am\u00e9ricas International Airport",
      "Mayor Buenaventura Vivas International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 9.04,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 37.99,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 899.92,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 369.91,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1548.19,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 628.06,
    Pays: "Dominican Republic",
    "Vol USD": 764.0,
    "S\u00e9jour USD": 985.0,
    "Sur place USD": 57.0,
    Latitude: 18.4801972,
    Longitude: -69.942111,
  },
  {
    City: "Manila",
    Air_Quality_Index: 150,
    Happiness_Score: 4.5,
    Cost_of_Living_Index: 45,
    Region: "Asia",
    Country: "Philippines",
    AvgTemperature: 27.5235688419,
    Traffic_enc: 3,
    IATA: ["MNL"],
    "Airport name": ["Ninoy Aquino International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 3.54,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 27.4,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 559.52,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 281.78,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1754.4,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 684.81,
    Pays: "Philippines",
    "Vol USD": 721.0,
    "S\u00e9jour USD": 2397.0,
    "Sur place USD": 36.0,
    Latitude: 14.5906346,
    Longitude: 120.9799964,
  },
  {
    City: "Jakarta",
    Air_Quality_Index: 155,
    Happiness_Score: 4.0,
    Cost_of_Living_Index: 40,
    Region: "Asia",
    Country: "Indonesia",
    AvgTemperature: 2.215782215,
    Traffic_enc: 3,
    IATA: ["CGK", "HLP", "PCB", "PPJ"],
    "Airport name": [
      "Soekarno-Hatta International Airport",
      "Halim Perdanakusuma International Airport",
      "Pondok Cabe Air Base",
      "Pulau Panjang Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 2.54,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 22.25,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 482.85,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 270.15,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1117.69,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 584.37,
    Pays: "Indonesia",
    "Vol USD": 710.0,
    "S\u00e9jour USD": 1381.0,
    "Sur place USD": 36.0,
    Latitude: -6.175247,
    Longitude: 106.8270488,
  },
  {
    City: "Kuala Lumpur",
    Air_Quality_Index: 160,
    Happiness_Score: 5.2,
    Cost_of_Living_Index: 55,
    Region: "Asia",
    Country: "Malaysia",
    AvgTemperature: 26.0850720675,
    Traffic_enc: 2,
    IATA: ["KUL"],
    "Airport name": ["Kuala Lumpur International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 3.33,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 22.2,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 426.7,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 274.24,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 974.11,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 523.27,
    Pays: "Malaysia",
    "Vol USD": 655.0,
    "S\u00e9jour USD": 2010.0,
    "Sur place USD": 34.0,
    Latitude: 3.1516964,
    Longitude: 101.6942371,
  },
  {
    City: "Taipei",
    Air_Quality_Index: 165,
    Happiness_Score: 5.8,
    Cost_of_Living_Index: 75,
    Region: "Asia",
    Country: "Taiwan",
    AvgTemperature: 20.741042521,
    Traffic_enc: 2,
    IATA: ["TPE"],
    "Airport name": ["Taiwan Taoyuan International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 5.82,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 38.77,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 663.07,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 429.98,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1455.64,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1005.23,
    Pays: "Taiwan",
    "Vol USD": 819.0,
    "S\u00e9jour USD": 1798.0,
    "Sur place USD": 62.0,
    Latitude: 25.0375198,
    Longitude: 121.5636796,
  },
  {
    City: "Shanghai",
    Air_Quality_Index: 170,
    Happiness_Score: 5.0,
    Cost_of_Living_Index: 80,
    Region: "Asia",
    Country: "China",
    AvgTemperature: 17.15168957,
    Traffic_enc: 3,
    IATA: ["PVG", "SHA"],
    "Airport name": [
      "Shanghai Pudong International Airport",
      "Shanghai Hongqiao International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 5.59,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 40.51,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1080.07,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 564.3,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2972.57,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1532.23,
    Pays: "China",
    "Vol USD": 546.0,
    "S\u00e9jour USD": 1711.0,
    "Sur place USD": 51.0,
    Latitude: 31.2323437,
    Longitude: 121.4691024,
  },
  {
    City: "Beijing",
    Air_Quality_Index: 175,
    Happiness_Score: 4.5,
    Cost_of_Living_Index: 85,
    Region: "Asia",
    Country: "China",
    AvgTemperature: 12.6222090318,
    Traffic_enc: 3,
    IATA: ["NAY", "PEK"],
    "Airport name": [
      "Beijing Nanyuan Airport",
      "Beijing Capital International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 4.19,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 30.73,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1176.59,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 660.6,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2732.46,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1426.41,
    Pays: "China",
    "Vol USD": 546.0,
    "S\u00e9jour USD": 1711.0,
    "Sur place USD": 51.0,
    Latitude: 39.9057136,
    Longitude: 116.3912972,
  },
  {
    City: "Karachi",
    Air_Quality_Index: 190,
    Happiness_Score: 3.0,
    Cost_of_Living_Index: 40,
    Region: "Asia",
    Country: "Pakistan",
    AvgTemperature: 25.5204892966,
    Traffic_enc: 3,
    IATA: ["KHI"],
    "Airport name": ["Jinnah International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 2.23,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 11.14,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 113.5,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 77.16,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 265.63,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 169.3,
    Pays: "Pakistan",
    "Vol USD": 928.0,
    "S\u00e9jour USD": 1912.0,
    "Sur place USD": 91.0,
    Latitude: 24.8546842,
    Longitude: 67.0207055,
  },
  {
    City: "Dhaka",
    Air_Quality_Index: 195,
    Happiness_Score: 2.5,
    Cost_of_Living_Index: 35,
    Region: "Asia",
    Country: "Bangladesh",
    AvgTemperature: -12.1611780455,
    Traffic_enc: 3,
    IATA: ["DAC"],
    "Airport name": ["Hazrat Shahjalal International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 1.87,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 11.24,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 136.4,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 84.27,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 333.63,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 200.14,
    Pays: "Bangladesh",
    "Vol USD": 1201.0,
    "S\u00e9jour USD": 1817.0,
    "Sur place USD": 58.0,
    Latitude: 23.7644025,
    Longitude: 90.389015,
  },
  {
    City: "Colombo",
    Air_Quality_Index: 200,
    Happiness_Score: 5.5,
    Cost_of_Living_Index: 45,
    Region: "Asia",
    Country: "Sri Lanka",
    AvgTemperature: 23.4674556923,
    Traffic_enc: 2,
    IATA: ["CMB", "RML"],
    "Airport name": [
      "Bandaranaike International Colombo Airport",
      "Colombo Ratmalana Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 1.36,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 10.85,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 295.69,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 113.04,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 560.22,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 227.75,
    Pays: "Sri Lanka",
    "Vol USD": 677.0,
    "S\u00e9jour USD": 1346.0,
    "Sur place USD": 50.0,
    Latitude: 6.9388614,
    Longitude: 79.8542005,
  },
  {
    City: "Islamabad",
    Air_Quality_Index: 205,
    Happiness_Score: 3.5,
    Cost_of_Living_Index: 40,
    Region: "Asia",
    Country: "Pakistan",
    AvgTemperature: 18.53619356,
    Traffic_enc: 3,
    IATA: ["ISB"],
    "Airport name": ["New Islamabad International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 1.34,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 15.59,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 164.65,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 106.92,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 400.0,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 231.87,
    Pays: "Pakistan",
    "Vol USD": 928.0,
    "S\u00e9jour USD": 1912.0,
    "Sur place USD": 91.0,
    Latitude: 33.6938118,
    Longitude: 73.0651511,
  },
  {
    City: "Hanoi",
    Air_Quality_Index: 220,
    Happiness_Score: 3.0,
    Cost_of_Living_Index: 35,
    Region: "Asia",
    Country: "Vietnam",
    AvgTemperature: 23.7429551287,
    Traffic_enc: 3,
    IATA: ["HAN"],
    "Airport name": ["Noi Bai International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 2.02,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 20.03,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 339.98,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 216.88,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 858.97,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 475.82,
    Pays: "Vietnam",
    "Vol USD": 710.0,
    "S\u00e9jour USD": 1692.0,
    "Sur place USD": 27.0,
    Latitude: 21.0283334,
    Longitude: 105.854041,
  },
  {
    City: "Perth",
    Air_Quality_Index: 50,
    Happiness_Score: 7.7,
    Cost_of_Living_Index: 110,
    Region: "Australia/South Pacific",
    Country: "Australia",
    AvgTemperature: 16.8059033024,
    Traffic_enc: 0,
    IATA: ["JAD", "PER", "PSL"],
    "Airport name": [
      "Perth Jandakot Airport",
      "Perth International Airport",
      "Perth/Scone Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 16.77,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 67.06,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1187.86,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 933.42,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2022.13,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1425.96,
    Pays: "Australia",
    "Vol USD": 1201.0,
    "S\u00e9jour USD": 3908.0,
    "Sur place USD": 119.0,
    Latitude: -31.9558933,
    Longitude: 115.8605855,
  },
  {
    City: "Brisbane",
    Air_Quality_Index: 40,
    Happiness_Score: 7.9,
    Cost_of_Living_Index: 100,
    Region: "Australia/South Pacific",
    Country: "Australia",
    AvgTemperature: 20.0402726815,
    Traffic_enc: 0,
    IATA: ["ACF", "BNE"],
    "Airport name": [
      "Brisbane Archerfield Airport",
      "Brisbane International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 13.41,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 67.06,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1290.34,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1020.53,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2108.74,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1420.14,
    Pays: "Australia",
    "Vol USD": 1201.0,
    "S\u00e9jour USD": 3908.0,
    "Sur place USD": 119.0,
    Latitude: -27.4689682,
    Longitude: 153.0234991,
  },
  {
    City: "Canberra",
    Air_Quality_Index: 35,
    Happiness_Score: 8.0,
    Cost_of_Living_Index: 95,
    Region: "Australia/South Pacific",
    Country: "Australia",
    AvgTemperature: 13.0998273257,
    Traffic_enc: 0,
    IATA: ["CBR"],
    "Airport name": ["Canberra International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 15.42,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 73.77,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1371.43,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1141.94,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2439.39,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1784.98,
    Pays: "Australia",
    "Vol USD": 1201.0,
    "S\u00e9jour USD": 3908.0,
    "Sur place USD": 119.0,
    Latitude: -35.2975906,
    Longitude: 149.1012676,
  },
  {
    City: "Hamilton",
    Air_Quality_Index: 35,
    Happiness_Score: 8.2,
    Cost_of_Living_Index: 60,
    Region: "South/Central America & Carribean",
    Country: "Bermuda",
    AvgTemperature: 19.4284866873,
    Traffic_enc: 1,
    IATA: ["BDA", "HAB", "HAO", "HLT", "HLZ", "YHM"],
    "Airport name": [
      "L.F. Wade International Airport",
      "Marion County Rankin Fite Airport",
      "Butler Co Regional Airport - Hogan Field",
      "Hamilton Airport",
      "Hamilton International Airport",
      "John C. Munro Hamilton International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 29.0,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 150.0,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 3250.0,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 2050.0,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 6666.67,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 4325.0,
    Pays: "Bermuda",
    "Vol USD": 764.0,
    "S\u00e9jour USD": 2909.0,
    "Sur place USD": 230.0,
    Latitude: 43.2560802,
    Longitude: -79.8728583,
  },
  {
    City: "Denver",
    Air_Quality_Index: 50,
    Happiness_Score: 7.5,
    Cost_of_Living_Index: 95,
    Region: "North America",
    Country: "US",
    AvgTemperature: 9.7162679139,
    Traffic_enc: 1,
    IATA: ["APA", "BJC", "DEN"],
    "Airport name": [
      "Centennial Airport",
      "Rocky Mountain Metropolitan Airport",
      "Denver International Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 18.0,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 72.5,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1893.0,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1601.38,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 3436.84,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 2571.58,
    Pays: "US",
    "Vol USD": 611.0,
    "S\u00e9jour USD": 1538.0,
    "Sur place USD": 106.0,
    Latitude: 39.7392364,
    Longitude: -104.984862,
  },
  {
    City: "Frankfurt",
    Air_Quality_Index: 60,
    Happiness_Score: 7.3,
    Cost_of_Living_Index: 90,
    Region: "Europe",
    Country: "Germany",
    AvgTemperature: -25.3715479261,
    Traffic_enc: 1,
    IATA: [null],
    "Airport name": [null],
    "Meal, Inexpensive Restaurant (USD)": 14.02,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 59.73,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1152.38,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 894.37,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2188.58,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1582.48,
    Pays: "Germany",
    "Vol USD": 109.0,
    "S\u00e9jour USD": 948.0,
    "Sur place USD": 98.0,
    Latitude: 50.1106444,
    Longitude: 8.6820917,
  },
  {
    City: "Geneva",
    Air_Quality_Index: 35,
    Happiness_Score: 8.1,
    Cost_of_Living_Index: 120,
    Region: "Europe",
    Country: "Switzerland",
    AvgTemperature: 10.7674952634,
    Traffic_enc: 0,
    IATA: ["GVA"],
    "Airport name": ["Geneva Cointrin International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 26.42,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 126.81,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 2098.13,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1691.44,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 4289.25,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 3161.51,
    Pays: "Switzerland",
    "Vol USD": 93.0,
    "S\u00e9jour USD": 1281.0,
    "Sur place USD": 174.0,
    Latitude: 46.2017559,
    Longitude: 6.1466014,
  },
  {
    City: "Yerevan",
    Air_Quality_Index: 85,
    Happiness_Score: 5.8,
    Cost_of_Living_Index: 50,
    Region: "Europe",
    Country: "Russia",
    AvgTemperature: 12.0538851002,
    Traffic_enc: 1,
    IATA: ["EVN"],
    "Airport name": ["Zvartnots International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 7.5,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 37.52,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 965.5,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 650.54,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1556.73,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 925.63,
    Pays: "Russia",
    "Vol USD": 207.0,
    "S\u00e9jour USD": 1580.0,
    "Sur place USD": 80.0,
    Latitude: 40.1777112,
    Longitude: 44.5126233,
  },
  {
    City: "Zurich",
    Air_Quality_Index: 40,
    Happiness_Score: 8.2,
    Cost_of_Living_Index: 130,
    Region: "Europe",
    Country: "Switzerland",
    AvgTemperature: 9.4857903446,
    Traffic_enc: 0,
    IATA: ["ZRH"],
    "Airport name": ["Z\u00fcrich Airport"],
    "Meal, Inexpensive Restaurant (USD)": 26.42,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 126.81,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 2037.85,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1605.72,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 3904.22,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 2860.79,
    Pays: "Switzerland",
    "Vol USD": 93.0,
    "S\u00e9jour USD": 1281.0,
    "Sur place USD": 174.0,
    Latitude: 47.3744489,
    Longitude: 8.5410422,
  },
  {
    City: "Boston",
    Air_Quality_Index: 50,
    Happiness_Score: 7.1,
    Cost_of_Living_Index: 110,
    Region: "North America",
    Country: "US",
    AvgTemperature: 10.7976974276,
    Traffic_enc: 2,
    IATA: ["BOS"],
    "Airport name": ["General Edward Lawrence Logan International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 20.0,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 100.0,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 2691.67,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1959.38,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 5017.15,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 3357.41,
    Pays: "US",
    "Vol USD": 611.0,
    "S\u00e9jour USD": 1538.0,
    "Sur place USD": 106.0,
    Latitude: 42.3554334,
    Longitude: -71.060511,
  },
  {
    City: "Madrid",
    Air_Quality_Index: 70,
    Happiness_Score: 7.0,
    Cost_of_Living_Index: 85,
    Region: "Europe",
    Country: "Spain",
    AvgTemperature: 14.6891862724,
    Traffic_enc: 2,
    IATA: ["ECV", "MAD", "TOJ"],
    "Airport name": [
      "Cuatro Vientos Airport",
      "Adolfo Su\u00e1rez Madrid\u2013Barajas Airport",
      "Torrej\u00f3n Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 12.46,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 51.93,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1041.06,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 827.49,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 1781.48,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1287.54,
    Pays: "Spain",
    "Vol USD": 71.0,
    "S\u00e9jour USD": 453.0,
    "Sur place USD": 78.0,
    Latitude: 40.4167047,
    Longitude: -3.7035825,
  },
  {
    City: "Nairobi",
    Air_Quality_Index: 95,
    Happiness_Score: 5.0,
    Cost_of_Living_Index: 50,
    Region: "Africa",
    Country: "Kenya",
    AvgTemperature: -4.7488550136,
    Traffic_enc: 2,
    IATA: ["NBO", "WIL"],
    "Airport name": [
      "Jomo Kenyatta International Airport",
      "Nairobi Wilson Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 4.08,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 32.67,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 406.29,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 184.66,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 981.35,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 427.67,
    Pays: "Kenya",
    "Vol USD": 546.0,
    "S\u00e9jour USD": 1438.0,
    "Sur place USD": 63.0,
    Latitude: -1.30261485,
    Longitude: 36.8288420181,
  },
  {
    City: "Ottawa",
    Air_Quality_Index: 40,
    Happiness_Score: 7.5,
    Cost_of_Living_Index: 90,
    Region: "North America",
    Country: "Canada",
    AvgTemperature: 6.6349340468,
    Traffic_enc: 1,
    IATA: ["YOW", "YRO"],
    "Airport name": [
      "Ottawa Macdonald-Cartier International Airport",
      "Ottawa / Rockcliffe Airport",
    ],
    "Meal, Inexpensive Restaurant (USD)": 18.61,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 61.42,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1271.09,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1005.11,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 2021.86,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 1619.35,
    Pays: "Canada",
    "Vol USD": 764.0,
    "S\u00e9jour USD": 1998.0,
    "Sur place USD": 102.0,
    Latitude: 45.4208777,
    Longitude: -75.6901106,
  },
  {
    City: "Vancouver",
    Air_Quality_Index: 35,
    Happiness_Score: 7.6,
    Cost_of_Living_Index: 110,
    Region: "North America",
    Country: "Canada",
    AvgTemperature: 10.2093445368,
    Traffic_enc: 1,
    IATA: ["YDT", "YVR"],
    "Airport name": ["Boundary Bay Airport", "Vancouver International Airport"],
    "Meal, Inexpensive Restaurant (USD)": 18.24,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 85.62,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 1804.36,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 1509.65,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 3362.22,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 2356.76,
    Pays: "Canada",
    "Vol USD": 764.0,
    "S\u00e9jour USD": 1998.0,
    "Sur place USD": 102.0,
    Latitude: 49.2608724,
    Longitude: -123.113952,
  },
  {
    City: "Zagreb",
    Air_Quality_Index: 75,
    Happiness_Score: 6.9,
    Cost_of_Living_Index: 65,
    Region: "Europe",
    Country: "Croatia",
    AvgTemperature: 8.2936739222,
    Traffic_enc: 1,
    IATA: ["ZAG"],
    "Airport name": ["Zagreb Airport"],
    "Meal, Inexpensive Restaurant (USD)": 9.63,
    "Meal for 2 People, Mid-range Restaurant, Three-course (USD)": 46.0,
    "Rent per month Apartment (1 bedroom) in City Centre (USD)": 574.94,
    "Rent per month Apartment (1 bedroom) Outside of Centre (USD)": 418.29,
    "Rent per month Apartment (3 bedrooms) in City Centre (USD)": 941.49,
    "Rent per month Apartment (3 bedrooms) Outside of Centre (USD)": 666.24,
    Pays: "Croatia",
    "Vol USD": 158.0,
    "S\u00e9jour USD": 467.0,
    "Sur place USD": 70.0,
    Latitude: 45.8130967,
    Longitude: 15.9772795,
  },
];

export default destination;
